starting
Job is running on node c1.ib.local
c1.ib.local
c1.ib.local
c1.ib.local
c1.ib.local
c1.ib.local
c1.ib.local
c1.ib.local
c1.ib.local
c1.ib.local
c1.ib.local
c1.ib.local
c1.ib.local
c1.ib.local
c1.ib.local
c1.ib.local
c1.ib.local
c1.ib.local
c1.ib.local
c1.ib.local
c1.ib.local
c1.ib.local
c1.ib.local
c1.ib.local
/home/users/ksf293/aemulator/code
Running in /home/users/ksf293/aemulator/code/..
Running in /home/users/ksf293/aemulator
Traceback (most recent call last):
  File "/home/users/ksf293/aemulator/code/run_chain_mock.py", line 161, in <module>
    main(args.config_fn)
  File "/home/users/ksf293/aemulator/code/run_chain_mock.py", line 15, in main
    chain_params_fn = initialize_chain.main(config_fn, overwrite_param_file=True)
  File "/home/users/ksf293/aemulator/code/initialize_chain.py", line 21, in main
    assert path.isfile(config_fname), "%s is not a valid config filename."%config_fname
AssertionError: ../chains/configs/chains_wp_xi_xi2_mcf_upf_uchuu_Msatmocks_covglam4_allmaxscale6.cfg is not a valid config filename.
done
